from .user import *
from .articles import *
from .client import *
from .partenaire import *
from .bon import *
from .auth import *
from .campagne import *
from .mytest import *
from .likesViews import *
from .view import *
from .loyaltyProgram import *