from .user import *
from .articles import *
from .client import *
from .partenaire import *
from .bon import *
from .campagne import *
from .mytest import *
from .signalMessage import *
from .loyaltyProgram import *
from .points import *