# Generated by Django 4.2.6 on 2023-11-08 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('firstName', models.CharField(blank=True, max_length=100)),
                ('lastName', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(default='email', max_length=254, unique=True, verbose_name='email address')),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'api_lycs_fid_user',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_lycs_fid_client',
            },
            bases=('api_lycs_fid.user',),
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('groupe', models.CharField(blank=True, max_length=100)),
                ('sousGroupe', models.CharField(blank=True, max_length=100)),
                ('ninea', models.CharField(blank=True, max_length=100)),
                ('confirmation_token', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'api_lycs_fid_partner',
            },
            bases=('api_lycs_fid.user',),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateDebutPromo', models.DateTimeField(default=django.utils.timezone.now)),
                ('dateFinPromo', models.DateTimeField(default=django.utils.timezone.now)),
                ('nomArticle', models.CharField(max_length=250)),
                ('reduction', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=512)),
                ('prixDeVente', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('partnerId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_lycs_fid.partner')),
            ],
            options={
                'db_table': 'api_lycs_fid_article',
            },
        ),
    ]
