# Generated by Django 4.2.6 on 2024-01-10 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('firstName', models.CharField(blank=True, max_length=100)),
                ('lastName', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(default='email', max_length=254, unique=True, verbose_name='email address')),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'api_lycs_fid_user',
            },
        ),
        migrations.CreateModel(
            name='LoyaltyTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.IntegerField()),
                ('equiPoints', models.IntegerField()),
                ('archived', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'api_lycs_fid_Paliers',
            },
        ),
        migrations.CreateModel(
            name='Mystest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'api_lycs_fid_test',
            },
        ),
        migrations.CreateModel(
            name='SignalMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('age', models.CharField(blank=True, choices=[('ADULTE', 'Adulte'), ('ENFANT', 'Enfant')], max_length=250)),
                ('sexe', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=250)),
                ('archived', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'api_lycs_fid_client',
            },
            bases=('api_lycs_fid.user',),
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('contactRef', models.CharField(blank=True, max_length=100)),
                ('groupe', models.CharField(blank=True, max_length=100)),
                ('sousGroupe', models.CharField(blank=True, max_length=100)),
                ('ninea', models.CharField(blank=True, max_length=100)),
                ('archived', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'api_lycs_fid_partner',
            },
            bases=('api_lycs_fid.user',),
        ),
        migrations.CreateModel(
            name='LoyaltyProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiers', models.ManyToManyField(to='api_lycs_fid.loyaltytier')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_lycs_fid_loyaltyProgram',
            },
        ),
        migrations.CreateModel(
            name='Campagne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateDebut', models.DateTimeField(default=django.utils.timezone.now)),
                ('dateFin', models.DateTimeField(default=django.utils.timezone.now)),
                ('nomCampagne', models.CharField(max_length=250)),
                ('codePromo', models.CharField(max_length=250)),
                ('ageCible', models.CharField(blank=True, choices=[('0-10 ans', '0 à 10 ans'), ('10-20 ans', '10 à 20 ans'), ('20-40 ans', '20 à 40 ans'), ('40-60 ans', '40 à 60 ans'), ('60plus', '60 ans et plus')], max_length=250)),
                ('sexeCilbe', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=250)),
                ('localisation', models.CharField(blank=True, default='adresse', max_length=250)),
                ('description', models.CharField(blank=True, max_length=512)),
                ('image', models.ImageField(blank=True, null=True, upload_to='myPucturs')),
                ('archived', models.BooleanField(default=False)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authorCamp', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='likesCamp', to=settings.AUTH_USER_MODEL)),
                ('views', models.ManyToManyField(blank=True, related_name='viewsCamp', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_lycs_fid_campagne',
            },
        ),
        migrations.CreateModel(
            name='BonReduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateDebut', models.DateTimeField(default=django.utils.timezone.now)),
                ('dateFin', models.DateTimeField(default=django.utils.timezone.now)),
                ('typeDeReduction', models.CharField(max_length=250)),
                ('codeDeReduction', models.CharField(blank=True, max_length=512)),
                ('montantDeReduction', models.IntegerField()),
                ('quantityBon', models.IntegerField()),
                ('ageCible', models.CharField(blank=True, choices=[('0-10 ans', '0 à 10 ans'), ('10-20 ans', '10 à 20 ans'), ('20-40 ans', '20 à 40 ans'), ('40-60 ans', '40 à 60 ans'), ('60plus ans', '60 ans et plus')], max_length=50)),
                ('sexeCible', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=250)),
                ('localisation', models.CharField(blank=True, default='adresse', max_length=250)),
                ('image', models.ImageField(blank=True, null=True, upload_to='myPucturs')),
                ('archived', models.BooleanField(default=False)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authorBon', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='likesBon', to=settings.AUTH_USER_MODEL)),
                ('views', models.ManyToManyField(blank=True, related_name='viewsBon', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_lycs_fid_bonReduction',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomArticle', models.CharField(max_length=250)),
                ('ageCible', models.CharField(blank=True, choices=[('0-10 ans', '0 à 10 ans'), ('10-20 ans', '10 à 20 ans'), ('20-40 ans', '20 à 40 ans'), ('40-60 ans', '40 à 60 ans'), ('60plus', '60 ans et plus')], max_length=20)),
                ('sexeCilbe', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='myPucturs')),
                ('archived', models.BooleanField(default=False)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL)),
                ('views', models.ManyToManyField(blank=True, related_name='views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_lycs_fid_article',
            },
        ),
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField()),
                ('date_attributed', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_received', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_given', to='api_lycs_fid.partner')),
            ],
        ),
    ]
