# Generated by Django 4.2.6 on 2024-01-08 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fcm_django', '0001_initial'),
        ('api_lycs_fid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='user_fcmdevice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fcm_django.fcmdevice'),
        ),
    ]
