# Generated by Django 4.2.6 on 2023-12-08 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_lycs_fid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bonreduction',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campagne',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partner',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
