# Generated by Django 4.2.6 on 2023-11-17 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_lycs_fid', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bonreduction',
            old_name='sexeCilbe',
            new_name='sexeCible',
        ),
    ]
