# Generated by Django 4.2.6 on 2023-11-22 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_lycs_fid', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='confirmation_token',
        ),
    ]
