# Generated by Django 4.2.6 on 2023-11-23 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_lycs_fid', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='myPucturs'),
        ),
        migrations.AlterField(
            model_name='bonreduction',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='myPucturs'),
        ),
        migrations.AlterField(
            model_name='campagne',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='myPucturs'),
        ),
    ]
