# Generated by Django 4.2.6 on 2023-12-20 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_lycs_fid', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loyaltytier',
            old_name='points',
            new_name='equiPoints',
        ),
        migrations.RenameField(
            model_name='loyaltytier',
            old_name='amount',
            new_name='montant',
        ),
        migrations.RemoveField(
            model_name='loyaltytier',
            name='loyaltyName',
        ),
        migrations.RemoveField(
            model_name='loyaltytier',
            name='reward',
        ),
    ]
