# Generated by Django 4.2.6 on 2023-11-02 10:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api_lycs_fid', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api_lycs_fid.user')),
            ],
            options={
                'db_table': 'api_lycs_fid_client',
            },
            bases=('api_lycs_fid.user',),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateDebutPromo', models.DateTimeField(default=django.utils.timezone.now)),
                ('dateFinPromo', models.DateTimeField(default=django.utils.timezone.now)),
                ('nomArticle', models.CharField(max_length=250)),
                ('reduction', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=512)),
                ('prixDeVente', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Article', to='api_lycs_fid.user')),
            ],
            options={
                'db_table': 'api_lycs_fid_article',
            },
        ),
    ]
