# Generated by Django 4.2.6 on 2023-12-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_lycs_fid', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loyaltytier',
            name='montant',
            field=models.IntegerField(),
        ),
    ]
