# Generated by Django 4.2.6 on 2024-01-10 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_lycs_fid', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='points',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_received', to='api_lycs_fid.client'),
        ),
    ]
