# Generated by Django 4.2.6 on 2023-12-11 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_lycs_fid', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignalMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
