# Generated by Django 4.2.6 on 2023-12-14 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_lycs_fid', '0002_signalmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='ageCible',
            field=models.CharField(blank=True, choices=[('0-10 ans', '0 à 10 ans'), ('10-20 ans', '10 à 20 ans'), ('20-40 ans', '20 à 40 ans'), ('40-60 ans', '40 à 60 ans'), ('60plus', '60 ans et plus')], max_length=20),
        ),
        migrations.AlterField(
            model_name='article',
            name='sexeCilbe',
            field=models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=10),
        ),
        migrations.AlterField(
            model_name='bonreduction',
            name='ageCible',
            field=models.CharField(blank=True, choices=[('0-10 ans', '0 à 10 ans'), ('10-20 ans', '10 à 20 ans'), ('20-40 ans', '20 à 40 ans'), ('40-60 ans', '40 à 60 ans'), ('60plus ans', '60 ans et plus')], max_length=50),
        ),
        migrations.AlterField(
            model_name='bonreduction',
            name='sexeCible',
            field=models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=250),
        ),
        migrations.AlterField(
            model_name='campagne',
            name='ageCible',
            field=models.CharField(blank=True, choices=[('0-10 ans', '0 à 10 ans'), ('10-20 ans', '10 à 20 ans'), ('20-40 ans', '20 à 40 ans'), ('40-60 ans', '40 à 60 ans'), ('60plus', '60 ans et plus')], max_length=250),
        ),
        migrations.AlterField(
            model_name='campagne',
            name='sexeCilbe',
            field=models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=250),
        ),
        migrations.AlterField(
            model_name='client',
            name='sexe',
            field=models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=250),
        ),
    ]
