# Generated by Django 4.2.6 on 2023-11-17 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_lycs_fid', '0002_rename_sexecilbe_bonreduction_sexecible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonreduction',
            name='ageCible',
            field=models.CharField(blank=True, choices=[('ADULTE', 'Adulte'), ('ENFANT', 'Enfant')], max_length=50),
        ),
        migrations.AlterField(
            model_name='bonreduction',
            name='sexeCible',
            field=models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=250),
        ),
        migrations.AlterField(
            model_name='campagne',
            name='ageCible',
            field=models.CharField(blank=True, choices=[('ADULTE', 'Adulte'), ('ENFANT', 'Enfant')], max_length=250),
        ),
        migrations.AlterField(
            model_name='campagne',
            name='sexeCilbe',
            field=models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=250),
        ),
        migrations.AlterField(
            model_name='client',
            name='age',
            field=models.CharField(blank=True, choices=[('ADULTE', 'Adulte'), ('ENFANT', 'Enfant')], max_length=250),
        ),
        migrations.AlterField(
            model_name='client',
            name='sexe',
            field=models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=250),
        ),
    ]
