# Generated by Django 4.2.6 on 2023-11-17 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_lycs_fid', '0002_rename_genre_client_sexe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bonreduction',
            old_name='author',
            new_name='authorBon',
        ),
        migrations.RenameField(
            model_name='campagne',
            old_name='author',
            new_name='authorCamp',
        ),
    ]
