# Generated by Django 4.2.6 on 2023-11-02 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_lycs_fid', '0003_alter_user_groups_alter_user_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='user',
        ),
        migrations.AddField(
            model_name='article',
            name='partnerId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_lycs_fid.partner'),
        ),
        migrations.AlterModelTable(
            name='user',
            table='api_lycs_fid_user',
        ),
    ]
