# Generated by Django 4.2.6 on 2023-11-17 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_lycs_fid', '0003_rename_author_bonreduction_authorbon_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bonreduction',
            old_name='authorBon',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='campagne',
            old_name='authorCamp',
            new_name='author',
        ),
    ]
