# Generated by Django 4.2.6 on 2023-11-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_lycs_fid', '0003_alter_bonreduction_agecible_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonreduction',
            name='sexeCible',
            field=models.CharField(blank=True, choices=[('H', 'Homme'), ('F', 'Femme')], max_length=250),
        ),
        migrations.AlterField(
            model_name='campagne',
            name='ageCible',
            field=models.CharField(blank=True, choices=[('ADULTE', 'Homme'), ('ENFANT', 'Femme')], max_length=250),
        ),
        migrations.AlterField(
            model_name='campagne',
            name='sexeCilbe',
            field=models.CharField(blank=True, choices=[('H', 'Masculin'), ('F', 'Féminin')], max_length=250),
        ),
        migrations.AlterField(
            model_name='client',
            name='sexe',
            field=models.CharField(blank=True, choices=[('H', 'Homme'), ('F', 'Femme')], max_length=250),
        ),
    ]
