# Generated by Django 4.2.6 on 2023-11-18 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_lycs_fid', '0004_alter_bonreduction_sexecible_alter_campagne_agecible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='contactRef',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
