# Generated by Django 4.2.6 on 2023-11-07 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_lycs_fid', '0005_alter_user_email_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_confimerd',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='confirmation_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='is_confimerd',
            field=models.BooleanField(default=False),
        ),
    ]
