# Generated by Django 4.2.6 on 2023-11-18 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_lycs_fid', '0005_partner_contactref'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mystest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'api_lycs_fid_test',
            },
        ),
    ]
